import type { StructuredReport } from '@/app/types';

export async function downloadPDF(
  report: StructuredReport,
  productName: string,
  founderName: string
): Promise<void> {
  const { default: jsPDF } = await import('jspdf');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const H = 297;
  const margin = 20;
  const contentW = W - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    // Dark background + accent bar on each page
    doc.setFillColor(18, 18, 20);
    doc.rect(0, 0, W, H, 'F');
    doc.setFillColor(99, 102, 241);
    doc.rect(0, 0, 6, H, 'F');
    return margin;
  };

  const sectionHeader = (title: string, color: [number, number, number]) => {
    doc.setFillColor(...color);
    doc.rect(margin, y, 4, 7, 'F');
    doc.setTextColor(...color);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin + 7, y + 5.5);
    y += 12;
  };

  const bodyText = (text: string) => {
    doc.setTextColor(190, 190, 210);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(text.replace(/\*\*/g, '').replace(/`/g, ''), contentW - 8);
    for (const line of lines) {
      if (y > H - 25) { y = addPage(); }
      doc.text(line, margin + 6, y);
      y += 5;
    }
    y += 4;
  };

  // ── Cover Page ────────────────────────────────────────────────────────────
  doc.setFillColor(18, 18, 20);
  doc.rect(0, 0, W, H, 'F');
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, 6, H, 'F');

  doc.setFillColor(99, 102, 241);
  doc.roundedRect(margin, 30, 14, 14, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.text('QCE', margin + 2.5, 39);

  doc.setTextColor(160, 160, 180);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('QWEN CO-FOUNDER ENGINE', margin + 18, 39);

  doc.setTextColor(240, 240, 255);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  const nameLines = doc.splitTextToSize(productName || 'Product Analysis', contentW);
  doc.text(nameLines, margin, 80);

  doc.setTextColor(100, 100, 120);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('WAR ROOM CO-FOUNDER REPORT', margin, 80 + nameLines.length * 12 + 8);

  const metaY = 140;
  const metas: [string, string][] = [
    ['FOUNDER', founderName],
    ['DATE', new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })],
    ['ENGINE', 'Qwen AI · Alibaba Cloud DashScope'],
    ['SENTIMENT', (report.worthinessScore?.sentiment || 'N/A').toUpperCase()],
  ];
  metas.forEach(([label, value], i) => {
    doc.setTextColor(80, 80, 100);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text(label, margin, metaY + i * 12);
    doc.setTextColor(200, 200, 220);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(value, margin + 35, metaY + i * 12);
  });

  if (report.worthinessScore) {
    const ws = report.worthinessScore;
    const gaugeY = 215;
    doc.setTextColor(80, 80, 100);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text('WORTHINESS SCORES', margin, gaugeY);

    const scores: { label: string; value: number; x: number }[] = [
      { label: 'Overall', value: ws.overall, x: margin },
      { label: 'Technical', value: ws.technical, x: margin + 42 },
      { label: 'Market', value: ws.market, x: margin + 84 },
      { label: 'Security', value: ws.security, x: margin + 126 },
    ];
    scores.forEach(({ label, value, x }) => {
      doc.setFillColor(40, 40, 50);
      doc.roundedRect(x, gaugeY + 4, 36, 20, 2, 2, 'F');
      doc.setFillColor(99, 102, 241);
      doc.roundedRect(x, gaugeY + 4, 36 * (value / 100), 20, 2, 2, 'F');
      doc.setTextColor(240, 240, 255);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`${value}`, x + 4, gaugeY + 16);
      doc.setTextColor(120, 120, 140);
      doc.setFontSize(6);
      doc.setFont('helvetica', 'normal');
      doc.text(label, x + 4, gaugeY + 21);
    });

    doc.setTextColor(160, 160, 200);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    const summaryLines = doc.splitTextToSize(`"${ws.summary}"`, contentW);
    doc.text(summaryLines, margin, gaugeY + 34);
  }

  doc.setTextColor(50, 50, 70);
  doc.setFontSize(7);
  doc.text('Confidential · Generated by Qwen Co-Founder Engine', margin, H - 12);

  // ── Page 2: Agent Analyses ───────────────────────────────────────────────
  y = addPage();

  doc.setTextColor(240, 240, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('AGENT WAR ROOM ANALYSES', margin, y);
  y += 12;

  sectionHeader('ATLAS — AI CTO VERDICT', [99, 102, 241]);
  bodyText(report.agentsFeedback.ctoAnalysis);
  sectionHeader('REX — INFRASTRUCTURE ASSESSMENT', [217, 119, 6]);
  bodyText(report.agentsFeedback.infraAnalysis);

  if (y > H - 60) { y = addPage(); }

  sectionHeader('NOVA — PRODUCT STRATEGY', [16, 185, 129]);
  bodyText(report.agentsFeedback.productAnalysis);
  sectionHeader('CIPHER — SECURITY AUDIT', [6, 182, 212]);
  bodyText(report.agentsFeedback.securityAnalysis);

  // ── Page 3: Market Feasibility ────────────────────────────────────────────
  y = addPage();

  doc.setTextColor(240, 240, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('MARKET FEASIBILITY REPORT', margin, y);
  y += 12;

  sectionHeader('TAM / SAM / SOM MARKET STUDY', [99, 102, 241]);
  bodyText(report.marketFeasibility.marketSizeStudy);
  sectionHeader('ARR PROJECTION', [16, 185, 129]);
  bodyText(report.marketFeasibility.expectedProfitARR);
  sectionHeader('RISK MITIGATION', [239, 68, 68]);
  bodyText(report.marketFeasibility.riskMitigation);

  doc.setTextColor(50, 50, 70);
  doc.setFontSize(7);
  doc.text('Confidential · Generated by Qwen Co-Founder Engine', margin, H - 12);

  const filename = `${(productName || 'report').toLowerCase().replace(/\s+/g, '-')}-war-room.pdf`;
  doc.save(filename);
}
